################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_SRCS := 
ASM_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
EXECUTABLES := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
tests/uart \
tests/switch \
tests/switch/Debug \
tests/spiflash \
tests/sd \
tests/led \
tests/led/Debug \
tests/lcd-osd9616 \
tests/lcd-osd9616/Debug \
tests/biosexamplePristine \
tests/biosexamplePristine/Debug \
tests/biosexample \
tests/biosexample/Debug \
tests/biosInClassExample \
tests/biosInClassExample/Debug \
tests/aic3204 \
tests/aic3204/Debug \
lib/bsl \
c55xx_csl/src \
c55xx_csl/drivers/sdio/src \
c55xx_csl/drivers/sdio/example \
c55xx_csl/ccs_v4.0_examples/wdt/CSL_WDT_Example \
c55xx_csl/ccs_v4.0_examples/usb/CSL_USB_PollExample \
c55xx_csl/ccs_v4.0_examples/usb/CSL_USB_MSC_pollExample \
c55xx_csl/ccs_v4.0_examples/usb/CSL_USB_MSC_fullSpeedExample \
c55xx_csl/ccs_v4.0_examples/usb/CSL_USB_MSC_dmaExample \
c55xx_csl/ccs_v4.0_examples/usb/CSL_USB_IntcExample \
c55xx_csl/ccs_v4.0_examples/usb/CSL_USB_DmaExample \
c55xx_csl/ccs_v4.0_examples/usb/CSL_USB_CdcExample \
c55xx_csl/ccs_v4.0_examples/uart/CSL_UART_pollExample \
c55xx_csl/ccs_v4.0_examples/uart/CSL_UART_dmaExample \
c55xx_csl/ccs_v4.0_examples/uart/CSL_UART_IntExample \
c55xx_csl/ccs_v4.0_examples/spi/CSL_SPI_Example \
c55xx_csl/ccs_v4.0_examples/sar/CSL_SAR_PollExample \
c55xx_csl/ccs_v4.0_examples/sar/CSL_SAR_IntcExample \
c55xx_csl/ccs_v4.0_examples/sar/CSL_SAR_DmaExample \
c55xx_csl/ccs_v4.0_examples/rtc/CSL_RTC_Example \
c55xx_csl/ccs_v4.0_examples/rtc/CSL_RTC_Compensation_Example \
c55xx_csl/ccs_v4.0_examples/pll/CSL_PLL_Example \
c55xx_csl/ccs_v4.0_examples/nand/CSL_NAND_PollExample \
c55xx_csl/ccs_v4.0_examples/nand/CSL_NAND_IntrExample \
c55xx_csl/ccs_v4.0_examples/nand/CSL_NAND_DmaWordSwapExample \
c55xx_csl/ccs_v4.0_examples/nand/CSL_NAND_DmaExample \
c55xx_csl/ccs_v4.0_examples/mmc_sd/CSL_MMCSD_intrExample \
c55xx_csl/ccs_v4.0_examples/mmc_sd/CSL_MMCSD_dmaExample \
c55xx_csl/ccs_v4.0_examples/mmc_sd/CSL_MMCSD_SdCardFSExtExample \
c55xx_csl/ccs_v4.0_examples/mmc_sd/CSL_MMCSD_SdCardFSExample \
c55xx_csl/ccs_v4.0_examples/mmc_sd/CSL_MMCSD_SdCardExample \
c55xx_csl/ccs_v4.0_examples/mmc_sd/CSL_MMCSD_MmcCardExample \
c55xx_csl/ccs_v4.0_examples/memory/CSL_MSDRAM_ClockSwitchExample \
c55xx_csl/ccs_v4.0_examples/memory/CSL_MEMORY_SARAM_RetentionExample \
c55xx_csl/ccs_v4.0_examples/memory/CSL_MEMORY_SARAM_PartialRetentionExample \
c55xx_csl/ccs_v4.0_examples/memory/CSL_MEMORY_DARAM_RetentionExample \
c55xx_csl/ccs_v4.0_examples/memory/CSL_MEMORY_DARAM_PartialRetentionExample \
c55xx_csl/ccs_v4.0_examples/lcd/CSL_LCDC_TextDisplayExample \
c55xx_csl/ccs_v4.0_examples/lcd/CSL_LCDC_DmaPolledExample \
c55xx_csl/ccs_v4.0_examples/lcd/CSL_LCDC_DmaIntcExample \
c55xx_csl/ccs_v4.0_examples/lcd/CSL_LCDC_DiagramExample \
c55xx_csl/ccs_v4.0_examples/lcd/CSL_LCDC_65kColorModeExample \
c55xx_csl/ccs_v4.0_examples/lcd/CSL_LCDC_262kColorModeExample \
c55xx_csl/ccs_v4.0_examples/intc/CSL_INTC_Example \
c55xx_csl/ccs_v4.0_examples/i2s/CSL_I2S_PollExample \
c55xx_csl/ccs_v4.0_examples/i2s/CSL_I2S_INTCExample \
c55xx_csl/ccs_v4.0_examples/i2s/CSL_I2S_DMAExampale \
c55xx_csl/ccs_v4.0_examples/i2c/CSL_I2C_PollExample \
c55xx_csl/ccs_v4.0_examples/i2c/CSL_I2C_LoopbackExample \
c55xx_csl/ccs_v4.0_examples/i2c/CSL_I2C_IntcExample \
c55xx_csl/ccs_v4.0_examples/i2c/CSL_I2C_DmaWordSwapExapmle \
c55xx_csl/ccs_v4.0_examples/i2c/CSL_I2C_DmaExample \
c55xx_csl/ccs_v4.0_examples/gpt/CSL_GPTExample \
c55xx_csl/ccs_v4.0_examples/gpio/CSL_GPIO_OutputPinExample \
c55xx_csl/ccs_v4.0_examples/gpio/CSL_GPIO_InputPinExample \
c55xx_csl/ccs_v4.0_examples/drv/atafs/src \
c55xx_csl/ccs_v4.0_examples/dma/CSL_DMA_StopAPIExample \
c55xx_csl/ccs_v4.0_examples/dma/CSL_DMA_PollExample \
c55xx_csl/ccs_v4.0_examples/dma/CSL_DMA_PingPongExample \
c55xx_csl/ccs_v4.0_examples/dma/CSL_DMA_IntcExample \
c55xx_csl/ccs_v4.0_examples/dat/CSL_DAT_Example \
c55xx_csl/ccs_v3.3_examples/wdt \
c55xx_csl/ccs_v3.3_examples/usb/example6 \
c55xx_csl/ccs_v3.3_examples/usb/example4/csl_usb_msc_poll_example \
c55xx_csl/ccs_v3.3_examples/usb/example4/csl_usb_msc_fullspeed_example \
c55xx_csl/ccs_v3.3_examples/usb/example4/csl_usb_msc_dma_example \
c55xx_csl/ccs_v3.3_examples/usb/example4 \
c55xx_csl/ccs_v3.3_examples/usb/example4/atafs/src \
c55xx_csl/ccs_v3.3_examples/usb/example3 \
c55xx_csl/ccs_v3.3_examples/usb/example2 \
c55xx_csl/ccs_v3.3_examples/usb/example1 \
c55xx_csl/ccs_v3.3_examples/uart/example3 \
c55xx_csl/ccs_v3.3_examples/uart/example2 \
c55xx_csl/ccs_v3.3_examples/uart/example1 \
c55xx_csl/ccs_v3.3_examples/spi \
c55xx_csl/ccs_v3.3_examples/sar/example3 \
c55xx_csl/ccs_v3.3_examples/sar/example2 \
c55xx_csl/ccs_v3.3_examples/sar/example1 \
c55xx_csl/ccs_v3.3_examples/rtc/example2 \
c55xx_csl/ccs_v3.3_examples/rtc/example1 \
c55xx_csl/ccs_v3.3_examples/pll \
c55xx_csl/ccs_v3.3_examples/nand/example4 \
c55xx_csl/ccs_v3.3_examples/nand/example3 \
c55xx_csl/ccs_v3.3_examples/nand/example2 \
c55xx_csl/ccs_v3.3_examples/nand/example1 \
c55xx_csl/ccs_v3.3_examples/mmc_sd/example6 \
c55xx_csl/ccs_v3.3_examples/mmc_sd/example6/atafs/src \
c55xx_csl/ccs_v3.3_examples/mmc_sd/example5 \
c55xx_csl/ccs_v3.3_examples/mmc_sd/example4 \
c55xx_csl/ccs_v3.3_examples/mmc_sd/example4/atafs/src \
c55xx_csl/ccs_v3.3_examples/mmc_sd/example3 \
c55xx_csl/ccs_v3.3_examples/mmc_sd/example2 \
c55xx_csl/ccs_v3.3_examples/mmc_sd/example1 \
c55xx_csl/ccs_v3.3_examples/memory/example5 \
c55xx_csl/ccs_v3.3_examples/memory/example4 \
c55xx_csl/ccs_v3.3_examples/memory/example3 \
c55xx_csl/ccs_v3.3_examples/memory/example2 \
c55xx_csl/ccs_v3.3_examples/memory/example1 \
c55xx_csl/ccs_v3.3_examples/lcd/example6 \
c55xx_csl/ccs_v3.3_examples/lcd/example5 \
c55xx_csl/ccs_v3.3_examples/lcd/example4 \
c55xx_csl/ccs_v3.3_examples/lcd/example3 \
c55xx_csl/ccs_v3.3_examples/lcd/example2 \
c55xx_csl/ccs_v3.3_examples/lcd/example1 \
c55xx_csl/ccs_v3.3_examples/intc \
c55xx_csl/ccs_v3.3_examples/i2s/example3 \
c55xx_csl/ccs_v3.3_examples/i2s/example2 \
c55xx_csl/ccs_v3.3_examples/i2s/example1 \
c55xx_csl/ccs_v3.3_examples/i2c/example5 \
c55xx_csl/ccs_v3.3_examples/i2c/example4 \
c55xx_csl/ccs_v3.3_examples/i2c/example3 \
c55xx_csl/ccs_v3.3_examples/i2c/example2 \
c55xx_csl/ccs_v3.3_examples/i2c/example1 \
c55xx_csl/ccs_v3.3_examples/gpt \
c55xx_csl/ccs_v3.3_examples/gpio/example2 \
c55xx_csl/ccs_v3.3_examples/gpio/example1 \
c55xx_csl/ccs_v3.3_examples/dma/example4 \
c55xx_csl/ccs_v3.3_examples/dma/example3 \
c55xx_csl/ccs_v3.3_examples/dma/example2 \
c55xx_csl/ccs_v3.3_examples/dma/example1 \
c55xx_csl/ccs_v3.3_examples/dat \
boot_post_SDcard/boot_post \

